#!/bin/bash
echo -e '\033[0;33;1mWaring continue: Y/N \033[0m'
read resu
if [ $resu == "N" ] || [ $resu == "n" ] ; then
    exit
fi

adb shell mv  /data/system/access_control.key  /data/system/access_control.key.bkup
echo "Clean access control，Done！"

adb shell mv  /data/system/gesture.key /data/system/gesture.key.bkup
echo "Clean gesture，Done！"

adb shell mv  /data/system/password.key /data/system/password.key.bkup
echo "Clean password，Done！"
