#!/bin/bash
source basic-method.sh
PKG_NAME=$1
if [ ! $PKG_NAME ]; then
	echo "------------------------OOPS:(  Please tell me which pkg! ------------------------"
	exit
fi

if [ $PKG_NAME ];then
    adb shell pm clear $1
fi
