#!/bin/bash
function get_current_pkg()
{
	adb shell "dumpsys window windows" | grep -E 'mFocusedApp' | awk -F/ '{print $1}' | awk -F"ActivityRecord" '{print $2}' | awk '{print $3}'
}

pkg_name="${1}"
if [ ! "${pkg_name}" ]; then
    pkg_name=$(get_current_pkg)

    echo
    echo
	echo "===================================="
    echo "no input, using \"${pkg_name}\""
	echo "===================================="
    echo
    echo
fi

adb shell dumpsys gfxinfo "${pkg_name}"
