#!/bin/bash
source basic-method.sh

pkg_name="${1}"
if [ ! "${pkg_name}" ]; then
    pkg_name=$(get_current_pkg)

	echo
	echo
	echo "===================================="
	echo "no input, using \"${pkg_name}\""
	echo "===================================="
	echo
	echo
fi

adb shell dumpsys gfxinfo "${pkg_name}"
