#!/bin/bash
#######functions######
function help_logcat()
{
	echo
	echo    "			Usage: logcat [OPTION]..."
	echo    "			Showing android device's log of the selected device"
	echo	"			TIPS: case nonsensitive"
	echo    "			OPTION:"
	echo    "			-d			name of the device: adb will connect this device"
	echo    "			-h			show all helps"
	echo	"			-p			package name: only show logs from this package"
	echo	"			-t			tag name: only show the log from this tag"
	echo	"			-v			key words: do not show lines that contains this key word"
	echo
	echo
}

function wrap_log_pid()
{
	if [ $1 ]; then
		echo "$1"
	fi
}

function choose_package()
{
    #get the section num of PID
    psresult=`adb shell ps | grep -v "\:" | sed '1!d'`
    for i in `seq 3`
    do
            lineresult=`echo $psresult | cut -d ' ' -f $i`
            if [ "$lineresult" == "PID" ]; then
                num=$i
                break
            fi
    done

    #get PID
    if [ "$OPTARG" ]; then
        PID=`adb shell ps |grep $OPTARG|awk '{print $'$num'}'`
	fi
	#
	tempWrappedIdFile=".tempWrappedIdFile"
	if [ "${PID}" ]; then
		echo "${PID}" | while read line
		do
			wrappedId=`wrap_log_pid $line`
			if [ "$multiPID" ]; then
				wrappedId="\|"$wrappedId
			fi
			multiPID="$multiPID$wrappedId"
			echo "$multiPID" > $tempWrappedIdFile
		done
	else
		return
	fi
	PID=`cat $tempWrappedIdFile`
	rm $tempWrappedIdFile
}

function show_process_log()
{
	choose_package
	######SHOW LOGS######
	echo "PID=\"${PID}\""
	if [ "${PID}" ]; then
	    command="$adb | grep \"${PID}\""
	    # echo "command={$command}"
	    eval "$command"
	else
		show_all_log
	fi
}

function hide_line()
{
	if [ !"$OPTARG" ]; then
		return
	elif [ "$SYS_USELESS_TAG" ]; then
		SYS_USELESS_TAG="$SYS_USELESS_TAG\|$OPTARG"
	else
		SYS_USELESS_TAG="$OPTARG"
	fi
}

function set_tag()
{
	if [ "$OPTARG" ]; then
		echo "TAG is $OPTARG"
		adb="$adb -s $OPTARG"
		eval "$adb"
	fi
}

function show_all_log()
{
	SYS_USELESS_TAG="\/AKMD2"
	SYS_USELESS_TAG+="\|\/MediaProvider"
	SYS_USELESS_TAG+="\|\/ExchangeService"
	SYS_USELESS_TAG+="\|\/libEGL"
	SYS_USELESS_TAG+="\|\/ThemeManager"
	SYS_USELESS_TAG+="\|\/PackageManager"
	SYS_USELESS_TAG+="\|\/LightsService"
	SYS_USELESS_TAG+="\|\/Yamaha-MC1N2-Audio"
	SYS_USELESS_TAG+="\|\/ConnectivityService"
	SYS_USELESS_TAG+="\|\/AudioService"
	SYS_USELESS_TAG+="\|\/SoundPool"
	SYS_USELESS_TAG+="\|\/StatusBar"
	SYS_USELESS_TAG+="\|\/cell"
	SYS_USELESS_TAG+="\|\/dalvikvm"
	SYS_USELESS_TAG+="\|\/NativeCrypto"
	SYS_USELESS_TAG+="\|\/BufferQueue"
	SYS_USELESS_TAG+="\|\/SurfaceTextureClient"
	SYS_USELESS_TAG+="\|\/ADB_SERVICES"
    SYS_USELESS_TAG+="\|\/MultiPhoneWindow:"
	SYS_USELESS_TAG+="\|\/TelephonyManagerEx"
	SYS_USELESS_TAG+="\|\/Telephony"
	SYS_USELESS_TAG+="\|\/IspDrv"
	SYS_USELESS_TAG+="\|\/PipeMgrDrv"
	SYS_USELESS_TAG+="\|\/WifiNative-wlan0"
	SYS_USELESS_TAG+="\|\/WifiCommon"
	SYS_USELESS_TAG+="\|\/WifiStateMachine"
	SYS_USELESS_TAG+="\|\/StateMachine"
	SYS_USELESS_TAG+="\|\/InputReader"
	SYS_USELESS_TAG+="\|\/SocketClient"
	SYS_USELESS_TAG+="\|\/iQiyiPushService"
	SYS_USELESS_TAG+="\|\/audio_hw_primary"
	SYS_USELESS_TAG+="\|\/SurfaceFlinger"
	SYS_USELESS_TAG+="\|\/WifiStateMachine"
	SYS_USELESS_TAG+="\|\/GmsNetworkLocationProvi"
	SYS_USELESS_TAG+="\|\/WifiService"
	SYS_USELESS_TAG+="\|\/ActivityManager"
	SYS_USELESS_TAG+="\|\/ConnectivityService"
	SYS_USELESS_TAG+="\|\/ConnectivityManager"
	SYS_USELESS_TAG+="\|\/GA-SERVICE"
	SYS_USELESS_TAG+="\|\/ClClient"
	SYS_USELESS_TAG+="\|\/wpa_supplicant"
	SYS_USELESS_TAG+="\|\/ThermalEngine"
	SYS_USELESS_TAG+="\|\/rmt_storage" #/system/bin/rmt_storage
	SYS_USELESS_TAG+="\|\/GpsLocationProvider(" #system_server
	SYS_USELESS_TAG+="\|\/TelephonyNetworkFactory" #com.android.phone
	SYS_USELESS_TAG+="\|I\/art\ \ \ \ \ ("
	SYS_USELESS_TAG+="\|I\/Choreographer("
	SYS_USELESS_TAG+="\|W\/Resources("
	SYS_USELESS_TAG+="\|I\/GmsBackupTransport("
	SYS_USELESS_TAG+="\|I\/PFTBT\ \ \ ("
	SYS_USELESS_TAG+="\|\/Finsky\ \ ("
	SYS_USELESS_TAG+="\|\/MarketUpdateReceiver("
	SYS_USELESS_TAG+="\|\/MobileDataStateTracker("



	echo "----------------------------LINES CONTAINS ONE OF FOLLOWING WILL BE HIDDEN:----------------------------"
	echo "-"
	echo "-"
	echo "-"
	SYS_USELESS_TAG_ECHO=${SYS_USELESS_TAG//\\/}
	SYS_USELESS_TAG_ECHO=${SYS_USELESS_TAG_ECHO//\//}
	echo -e "${SYS_USELESS_TAG_ECHO//\|/\n}"
	echo "-"
	echo "-"
	echo "-"
	echo "-------------------------------------------------------------------------------------------------------"
	SYS_USELESS_TAG=`echo $SYS_USELESS_TAG`
	eval "$adb | grep -iv \"${SYS_USELESS_TAG}\""
}

source basic-method.sh

has_device
check_device
adb devices
adb="adb -s $dev logcat -v color"
#clear logcat
#$adb -c;


if [ "$1" ];then
    while getopts "d:hp:t:v:" arg #选项后面的冒号表示该选项需要参数
    do
        case $arg in
             d)
                echo "device is $OPTARG"
                ;;
             h)
                help_logcat
                exit 0
                ;;
             p)
				show_process_log
                ;;
             t)
				set_tag
                ;;
             v)
				hide_line
				;;
             ?) echo
				echo
				echo "!!!unkown OPTION: -$arg"
				show_all_log
				echo
				echo
				exit 0
        esac
    done
else
	show_all_log
fi
