#!/bin/bash
#######functions######
function help_logcat()
{
	echo
	echo    "			Usage: logcat [OPTION]..."
	echo    "			Showing android device's log of the selected device"
	echo	"			TIPS: case nonsensitive"
	echo    "			OPTION:"
	echo    "			-d			name of the device: adb will connect this device"
	echo    "			-h			show all helps"
	echo	"			-p			package name: only show logs from this package"
	echo	"			-t			tag name: only show the log from this tag"
	echo	"			-v			key words: do not show lines that contains this key word"
	echo
	echo
}

function wrap_log_pid()
{
	if [ $1 ]; then
		echo "$1\)\:"
	fi
}

function choose_package()
{
    #get the section num of PID
    psresult=`adb shell ps | grep -v "\:" | sed '1!d'`
    for i in `seq 3`
    do
            lineresult=`echo $psresult | cut -d ' ' -f $i`
            if [ "$lineresult" == "PID" ]; then
                num=$i
                break
            fi
    done

    #get PID
    if [ "$OPTARG" ]; then
        #pid=`adb shell ps |grep $OPTARG | sed '1!d' |awk '{print $'$num'}'`
        pid=`adb shell ps |grep $OPTARG|awk '{print $'$num'}'`
	fi

	#
	tempWrappedIdFile=".tempWrappedIdFile"
	if [ "$pid" ]; then
		echo "$pid" | while read line
		do
			wrappedId=`wrap_log_pid $line`
			if [ "$multiPID" ]; then
				wrappedId="\|"$wrappedId
			fi
			multiPID="$multiPID$wrappedId"
			echo "$multiPID" > $tempWrappedIdFile
		done
	else
		return
	fi
	pid=`cat $tempWrappedIdFile`
	rm $tempWrappedIdFile
	echo "$pid"
}

function show_process_log()
{
	choose_package
	######SHOW LOGS######

	echo
	if [ "$pid" ]; then
	    $adb | grep $pid\)\:
	else
		show_all_log
	fi
}

function hide_line()
{
	if [ !"$OPTARG" ]; then
		return
	elif [ "$noneshow" ]; then
		noneshow="$noneshow\|$OPTARG"
	else
		noneshow="$OPTARG"
	fi
}

function set_tag()
{
	if [ "$OPTARG" ]; then
		echo "TAG is $OPTARG"
		adb="$adb -s $OPTARG"
	fi
}

function show_all_log()
{
	noneshow="\/AKMD2\|\/MediaProvider\|\/wpa_supplicant\|\/ExchangeService\|\/libEGL\|\/ThemeManager\|\/PackageManager\|\/LightsService\|\/Yamaha-MC1N2-Audio\|\/ConnectivityService\|W\/AudioService\|E\/SoundPool\|I\/wpa_supplicant\|D\/StatusBar\|D\/cell\|D\/dalvikvm\|\/NativeCrypto\|\/BufferQueue\|\/SurfaceTextureClient\|\/ADB_SERVICES\|\/TelephonyManagerEx\|\/IspDrv\|\/PipeMgrDrv\|\/WifiNative-wlan0\|\/WifiCommon\|\/WifiStateMachine\|\/StateMachine\|\/InputReader\|\/SocketClient\|\/iQiyiPushService\|\/audio_hw_primary\|\/SurfaceFlinger"
	echo "----------------------------LINES CONTAINS ONE OF FOLLOWING WILL NOT SHOW:----------------------------"
	echo "$noneshow"
	noneshow=`echo $noneshow`
	$adb | grep -iv "$noneshow"
}

source basic-method.sh

has_device
check_device
adb devices
adb="adb -s $dev logcat"
#pid of the selected package
pid=""

#clear logcat
#$adb -c;

if [ "$1" ];then
    while getopts "d:hp:t:v:" arg #选项后面的冒号表示该选项需要参数
    do
        case $arg in
             d)
                echo "device is $OPTARG"
                ;;
             h)
                help_logcat
                exit 0
                ;;
             p)
				show_process_log
                ;;
             t)
				set_tag
                ;;
             v)
				hide_line
				;;
             ?) echo
				echo
				echo "!!!unkown OPTION: -$arg"
				show_all_log
				echo
				echo
				exit 0
        esac
    done
else
	show_all_log
fi

