#!/bin/bash
#######functions######
function help_logcat()
{
	echo
	echo    "			Usage: logcat [OPTION]..."
	echo    "			Showing android device's log of the selected device"
	echo	"			TIPS: case nonsensitive"
	echo    "			OPTION:"
	echo    "			-d			name of the device: adb will connect this device"
	echo    "			-h			show all helps"
	echo	"			-p			package name: only show logs from this package"
	echo	"			-t			tag name: only show the log from this tag"
	echo	"			-v			key words: do not show lines that contains this key word"
	echo
	echo
}

function choose_package()
{
    #echo "start choose_package package = $OPTARG"
	#get process id of this package
    #psresult=`adb shell ps | sed '1!d'`
    psresult=`adb shell ps | grep -v "\:" | sed '1!d'`
    for i in `seq 3`
    do
            lineresult=`echo $psresult | cut -d ' ' -f $i`
            if [ "$lineresult" == "PID" ]; then
                num=$i
                echo "line is $num"
                break
            fi
    done
    if [ "$OPTARG" ]; then
        pid=`adb shell ps |grep $OPTARG | sed '1!d' |awk '{print $'$num'}'`
	fi
    echo "pid is $pid  num is $num"
	echo "done  choose_package pid = $pid pkg=$OPTARG"
}

function hide_line()
{
	if [ !"$OPTARG" ]; then
		return
	elif [ "$noneshow" ]; then
		noneshow="$noneshow\|$OPTARG"
	else
		noneshow="$OPTARG"
	fi
}

function set_tag(){
	if [ "$OPTARG" ]; then
		echo "TAG is $OPTARG"
		adb="$adb -s $OPTARG"
	fi
}

source basic-method
has_device
check_device
adb devices
adb="adb -s $dev logcat"
#pid of the selected package
pid=""
#clear logcat
$adb -c;


noneshow="\/AKMD2\|\/MediaProvider\|\/wpa_supplicant\|dalvikvm\|ExchangeService\|libEGL\|ThemeManager\|PackageManager\|LightsService\|Yamaha-MC1N2-Audio\|\/Yunio\|\/ConnectivityService\|W\/AudioService\|E\/SoundPool\|I\/wpa_supplicant\|D\/StatusBar\|D\/cell\|D\/dalvikvm\|\/NativeCrypto\|\/BufferQueue\|\/SurfaceTextureClient\|\/ADB_SERVICES\|\/TelephonyManagerEx\|\/IspDrv\|\/PipeMgrDrv\|\/IspDrv\|\/WifiNative-wlan0\|\/WifiCommon\|\/WifiStateMachine\|\/StateMachine\|\/InputReader\|\/SocketClient\|\/SurfaceFlinger"

if [ "$1" ];then
    while getopts "d:hp:t:v:" arg #选项后面的冒号表示该选项需要参数
    do
        case $arg in
             d)
                echo "device is $OPTARG"
                ;;
             h)
                help_logcat
                exit 0
                ;;
             p)
				choose_package
                ;;
             t)
				set_tag
                ;;
             v)
				hide_line
				;;
             ?) echo
				echo
				echo "!!!unkown OPTION: -$arg"
				echo
				echo
				exit
        esac
    done
fi

######SHOW LOGS######
if [ "$noneshow" ]; then
	echo
	echo "----------------------------LINES CONTAINS ONE OF FOLLOWING WILL NOT SHOW:----------------------------"
	echo
	echo "$noneshow"
	echo
fi
echo
echo
if [ "$pid" ]; then
    # echo "$adb			pid is $pid"
    $adb | grep $pid\)\:
else
	$adb | grep -iv $noneshow
fi

